"""empty message

Revision ID: b8f8baea8e2f
Revises: 965a28f8e910
Create Date: 2024-02-06 17:52:58.055531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f8baea8e2f'
down_revision = '965a28f8e910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barrels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'labs', ['lab'], ['id'])
        batch_op.drop_column('lab_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barrels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'labs', ['lab_id'], ['id'])
        batch_op.drop_column('lab')

    # ### end Alembic commands ###
